mode: train

seed: 0
accelerator: cuda
devices: 1
resume: False
wandb: True
tags: [pretraining]
exp_name: train_cifar100_resnet18
save_dir: /data/fszatkowski/sid/pretrained/cifar100/resnet18
workers: 8
save_every: 10
eval_every: 1

model_arch: resnet18_32
num_classes: 100
use_timm: False
pretrained: False
teacher_arch: None
teacher_ckpt: None

train_dataset: cifar100
test_dataset: cifar100
use_kornia: False

maxepochs: 100
batch_size_train: 512
batch_size_eval: 2048
learning_rate: 0.01
weight_decay: 0.05
optimizer: 'adamw'
scheduler: 'cosine'